
version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27018:27018"
  backend:
    build: ./node-backend/
    ports:
      - "8000:8000"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./react-frontend/
    ports:
      - "8080:8080"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend