
version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27018:27018"
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend